apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-to-infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/JFCasas/gitops-demo.git
        revision: master
        directories:
          - path: infra/*      # recorre cada subcarpeta de infra/
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: infra
      source:
        repoURL: https://github.com/JFCasas/gitops-demo.git
        targetRevision: master
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      
