apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
  labels:
    app: busybox2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: busybox2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
        - name: busybox2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: {{ toJson .Values.command }}
          resources: {{- toYaml .Values.resources | nindent 12 }}


