apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterSize: {{ .Values.clusterSize }}
  clusterVersion: {{ .Values.clusterVersion }}

  kubernetesConfig:
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
      limits:
        cpu: {{ .Values.resources.limits.cpu }}
        memory: {{ .Values.resources.limits.memory }}
    redisSecret:
      name: redis-secret
      key: password

  redisLeader:
    service:
      type: ClusterIP
  redisFollower:
    service:
      type: ClusterIP

  service:
    type: ClusterIP

  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.storage.storageClass }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}
